/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.contacts.view;

/**
 *
 * @author Edison Verdesoto, Code Warriors, DCCO-ESPE
 */
public class ContactsSystem extends javax.swing.JFrame {

    /**
     * Creates new form ContactsSystem
     */
    public ContactsSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mmuContacts = new javax.swing.JMenu();
        itmManagment = new javax.swing.JMenu();
        itmGo = new javax.swing.JMenuItem();
        itmContacst = new javax.swing.JMenuItem();
        itmCall = new javax.swing.JMenu();
        itmWhatsApp = new javax.swing.JMenuItem();
        itmMessenger = new javax.swing.JMenuItem();
        itmPhone = new javax.swing.JMenuItem();
        mmuSettings = new javax.swing.JMenu();
        itmModify = new javax.swing.JMenuItem();
        mmuHelp = new javax.swing.JMenu();
        itmAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 60));

        mmuContacts.setText("Contacts ");

        itmManagment.setText("Managment");

        itmGo.setText("Go");
        itmGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmGoActionPerformed(evt);
            }
        });
        itmManagment.add(itmGo);

        mmuContacts.add(itmManagment);

        itmContacst.setText("Contacts");
        mmuContacts.add(itmContacst);

        itmCall.setText("Call");

        itmWhatsApp.setText("WhatsApp");
        itmCall.add(itmWhatsApp);

        itmMessenger.setText("Messenger");
        itmCall.add(itmMessenger);

        itmPhone.setText("Phone");
        itmCall.add(itmPhone);

        mmuContacts.add(itmCall);

        jMenuBar1.add(mmuContacts);

        mmuSettings.setText("Settings");

        itmModify.setText("Modify");
        itmModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmModifyActionPerformed(evt);
            }
        });
        mmuSettings.add(itmModify);

        jMenuBar1.add(mmuSettings);

        mmuHelp.setText("Help");

        itmAbout.setText("About");
        mmuHelp.add(itmAbout);

        jMenuBar1.add(mmuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmGoActionPerformed
        FrmContacts frmContacts = new FrmContacts();
        frmContacts.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmGoActionPerformed

    private void itmModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmModifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmModifyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactsSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactsSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactsSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactsSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactsSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAbout;
    private javax.swing.JMenu itmCall;
    private javax.swing.JMenuItem itmContacst;
    private javax.swing.JMenuItem itmGo;
    private javax.swing.JMenu itmManagment;
    private javax.swing.JMenuItem itmMessenger;
    private javax.swing.JMenuItem itmModify;
    private javax.swing.JMenuItem itmPhone;
    private javax.swing.JMenuItem itmWhatsApp;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mmuContacts;
    private javax.swing.JMenu mmuHelp;
    private javax.swing.JMenu mmuSettings;
    // End of variables declaration//GEN-END:variables
}
