/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.mongodb.view;

import com.google.gson.Gson;
import com.mongodb.ConnectionString;
import com.mongodb.MongoClientSettings;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import com.mycompany.mongodb.Stereo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author USER
 */
public class frmStereo extends javax.swing.JFrame {

    private static final String CONNECTION_STRING = "mongodb+srv://JhordyM:JhordyM@cluster0.fiselec.mongodb.net/";
    private static MongoClient mongoClient;
    private static MongoDatabase database;
    private static MongoCollection<Document>collection;
    DefaultTableModel tableModel;
    private int id;
    private String name;
    private String company;
    private double price;
    private int selectedRow;
    Stereo stereo;
    
    /**
     * Creates new form frmStereo
     */
    public frmStereo() {
        ConnectionString connectionString = new ConnectionString(CONNECTION_STRING);
        MongoClientSettings settings = MongoClientSettings.builder()
                .applyConnectionString(connectionString)
                .build();
        mongoClient = MongoClients.create(settings);
        database = mongoClient.getDatabase("Stereo");
        collection = database.getCollection("Stereo");
        initComponents();
        this.setLocationRelativeTo(null);
        tableModel = (DefaultTableModel) tbStereo.getModel(); 
        tbStereo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnShow = new javax.swing.JButton();
        bntUpdtae = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtCompany = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbStereo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Stereo CRUD");

        btnShow.setText("Show databases");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        bntUpdtae.setText("Update");
        bntUpdtae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntUpdtaeActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        jLabel3.setText("NAME");

        jLabel4.setText("COMPANY");

        jLabel5.setText("PRICE");

        tbStereo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "name", "company", "price"
            }
        ));
        jScrollPane2.setViewportView(tbStereo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(bntUpdtae)
                            .addComponent(btnAdd)
                            .addComponent(btnDelete)
                            .addComponent(btnShow))
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(bntUpdtae)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdd)
                .addGap(12, 12, 12)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShow)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        MongoCursor<Document> cursor = collection.find().iterator();
        tableModel.setRowCount(0);
        while (cursor.hasNext()) {
            Document document = cursor.next();
            int id = document.getInteger("id");
            String name = document.getString("name");
            String company = document.getString("company"); // Update the data type to String
            double price = document.getDouble("price");
            Object[] row = {id, name, company, price};
            tableModel.addRow(row);
        }
    }//GEN-LAST:event_btnShowActionPerformed

    private void bntUpdtaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntUpdtaeActionPerformed
    String cell1 = txtID.getText();
    String cell2 = txtName.getText();
    String cell3 = txtCompany.getText();
    String cell4 = txtPrice.getText();
    
    if (cell1.isEmpty() || cell2.isEmpty() || cell3.isEmpty() || cell4.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe llenar todas las celdas", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try {
        // Obtener los datos ingresados
        int id = Integer.parseInt(txtID.getText());
        String name = txtName.getText();
        String company = txtCompany.getText(); // Actualizar el campo "company" como String
        double price = Double.parseDouble(txtPrice.getText());

        Document selectedDocument = collection.find(Filters.eq("id", id)).first();

        boolean articuloEncontrado = false;

        if (selectedDocument != null) {
            int selectedRow = tbStereo.getSelectedRow();

            selectedDocument.put("name", name);
            selectedDocument.put("company", company);
            selectedDocument.put("price", price);

            // Reemplazar el documento en la base de datos
            collection.replaceOne(Filters.eq("id", id), selectedDocument);

            // Actualizar los datos en la tabla
            tbStereo.setValueAt(id, selectedRow, 0);
            tbStereo.setValueAt(name, selectedRow, 1);
            tbStereo.setValueAt(company, selectedRow, 2);
            tbStereo.setValueAt(price, selectedRow, 3);

            JOptionPane.showMessageDialog(this, "Artículo actualizado correctamente");

            articuloEncontrado = true;
        }

        if (!articuloEncontrado) {
            JOptionPane.showMessageDialog(this, "El artículo no existe en la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese solo números en los campos ID y Precio", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_bntUpdtaeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String cell1 = txtID.getText();
        String cell2 = txtName.getText();
        String cell3 = txtCompany.getText();
        String cell4 = txtPrice.getText();
        if (cell1.isEmpty() || cell2.isEmpty() || cell3.isEmpty() || cell4.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe llenar todas las celdas", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int id = Integer.parseInt(cell1);
            if (checkIdExists(id)) {
                JOptionPane.showMessageDialog(this, "El ID ya existe si desea actualizar aplaste el boton Editar", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                readData();
                StringBuilder confirmationMessage = appendItems();
                int option = JOptionPane.showConfirmDialog(this, confirmationMessage.toString());

                if (option == JOptionPane.YES_OPTION) {
                    Gson gson = new Gson();
                    String json = gson.toJson(stereo);
                    Document document = Document.parse(json);
                    collection.insertOne(document);
                    JOptionPane.showMessageDialog(rootPane, "Guardado");
                    addToTable(stereo);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Cancelado");
                }
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        deleteSelectedItem();
    
    }//GEN-LAST:event_btnDeleteActionPerformed

    private StringBuilder appendItems() {
        StringBuilder confirmationMessage = new StringBuilder();
        confirmationMessage.append("Estas seguro de ingresar el siguiente producto?").append("\n\n");
        confirmationMessage.append("ID: ").append(stereo.getId()).append("\n");
        confirmationMessage.append("Name: ").append(stereo.getName()).append("\n");
        confirmationMessage.append("Company: ").append(stereo.getCompany()).append("\n"); // Actualizar el campo "company" como String
        confirmationMessage.append("Price: ").append(stereo.getPrice()).append("\n");

        return confirmationMessage;
}
    
    private boolean checkIdExists(int id) {
    Document query = new Document("id", id);
    return collection.countDocuments(query) > 0;
}
    
    private void deleteSelectedItem() {
    int selectedRow = tbStereo.getSelectedRow();

    if (selectedRow >= 0) {
        int id = (int) tbStereo.getValueAt(selectedRow, 0);

        int option = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar el artículo seleccionado?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            collection.deleteOne(Filters.eq("id", id));
            tableModel.removeRow(selectedRow);
            JOptionPane.showMessageDialog(this, "Artículo eliminado correctamente");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione un artículo para eliminar", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    
private void readData() throws NumberFormatException {
    int id;
    String name;
    String company;
    double price;

    id = Integer.parseInt(txtID.getText());
    name = txtName.getText();
    company = txtCompany.getText(); // Actualizar el campo "company" como String
    price = Double.parseDouble(txtPrice.getText());

    stereo = new Stereo(id, name, company, price);
}

    private void addToTable(Stereo stereo) {
        Object[] row = {stereo.getId(), stereo.getName(), stereo.getCompany(), stereo.getPrice()};
        tableModel.addRow(row);
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmStereo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmStereo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmStereo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmStereo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmStereo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntUpdtae;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbStereo;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
